#nginx config to proxy traffic into backend service
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream backend_upstream {
        server backend:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_upstream;
        }
    }

